# Generated by Django 3.2.9 on 2021-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Batch', models.CharField(choices=[('Info', 'Choose a batch'), ('Morning-1', '6-7AM'), ('Morning-2', '6-7AM'), ('Morning-3', '8-9AM'), ('Evening-1', '5-6PM')], default='Info', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_allowed_to_change_batch', models.BooleanField(default=False)),
                ('is_fees_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
