# Generated by Django 3.1.2 on 2021-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaForm', '0003_auto_20211114_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount',
            field=models.CharField(choices=[('Info', 'Choose Package'), ('Package-1', '500rs')], default='Info', max_length=20),
        ),
    ]
