# Generated by Django 3.1.2 on 2021-11-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaForm', '0004_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yogaform',
            name='Batch',
            field=models.CharField(choices=[('Info', 'Choose a batch'), ('Morning-1', '6AM-7AM'), ('Morning-2', '7AM-8AM'), ('Morning-3', '8AM-9AM'), ('Evening-4', '5PM-6PM')], default='Info', max_length=100),
        ),
    ]
