# Generated by Django 3.1.2 on 2021-11-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YogaForm', '0005_auto_20211117_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogaform',
            old_name='is_allowed_to_change_batch',
            new_name='cannot_change_batch',
        ),
    ]
